// scripts/fetch-strapi-config.ts
import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import 'dotenv/config';

const __dirname = dirname(fileURLToPath(import.meta.url));

const STRAPI_URL = process.env.PUBLIC_STRAPI_API_URL;
const STRAPI_TOKEN = process.env.PUBLIC_STRAPI_API_TOKEN;

if (!STRAPI_URL) {
  console.error('PUBLIC_STRAPI_API_URL environment variable is not set');
  process.exit(1);
}

interface StrapiLocale {
  code: string;
  name: string;
  isDefault?: boolean;
}

interface LocalesResult {
  data: StrapiLocale[];
  source: string;
}

// 仅使用 REST API 获取语言列表
async function fetchLocalesViaRestAPI(): Promise<LocalesResult | null> {
  console.log('\n🌐 Fetching locales via REST API...');
  try {
    const response = await fetch(`${STRAPI_URL}/api/i18n/locales`, {
      headers: STRAPI_TOKEN ? { Authorization: `Bearer ${STRAPI_TOKEN}` } : {}
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const data = await response.json();
    if (data && data.length > 0) {
      console.log(`✅ Successfully fetched ${data.length} locales via REST API`);
      const localesData = data.map((locale: any) => ({
        code: locale.code || '',
        name: locale.name || '',
        isDefault: locale.isDefault === true || locale.default === true,
      }));
      return { data: localesData, source: 'REST API' };
    }
    throw new Error('No locales data from REST API');
  } catch (error: any) {
    console.error('❌ REST API failed:', error.message);
    return null;
  }
}

// 通用语言名称后备（仅当 Strapi 未提供名称时使用）
function fallbackLocaleName(code: string): string {
  return code.charAt(0).toUpperCase() + code.slice(1);
}

// 通用区域格式规则（无硬编码）
function formatLocaleForIntl(locale: string): string {
  // 如果已经是语言-地区格式（如 en-US），直接返回
  if (/^[a-z]{2}-[A-Z]{2}$/.test(locale)) {
    return locale;
  }
  // 如果只是语言代码（如 en），转换为 en-EN
  if (/^[a-z]{2}$/.test(locale)) {
    return `${locale}-${locale.toUpperCase()}`;
  }
  // 其他情况（如带有 script 的变体）原样返回
  return locale;
}

// 生成配置文件
function generateConfig(localesData: StrapiLocale[], source: string): { locales: string[]; defaultLocale: string } {
  console.log(`\n📁 Generating configuration from: ${source}`);

  const validLocales = localesData
    .map(item => item.code?.trim())
    .filter((code): code is string => !!code);

  const uniqueLocales = [...new Set(validLocales)];
  if (uniqueLocales.length === 0) {
    throw new Error('No valid locale codes found');
  }

  // 确定默认语言
  let defaultLocale = uniqueLocales[0];
  const defaultItem = localesData.find(item => item.isDefault === true);
  if (defaultItem?.code) {
    defaultLocale = defaultItem.code;
  } else {
    console.warn(`⚠️ No default locale marker found, using first locale '${defaultLocale}' as default.`);
  }

  console.log(`📋 Found ${uniqueLocales.length} locales: ${uniqueLocales.join(', ')}`);
  console.log(`   Default locale: ${defaultLocale}`);

  // 创建 locale 详细信息
  const localeDetails = uniqueLocales.map(code => {
    const item = localesData.find(i => i.code === code);
    return {
      code,
      name: item?.name || fallbackLocaleName(code),
      isDefault: code === defaultLocale
    };
  });

  // 生成配置内容（内联通用区域格式函数，确保生成的文件独立）
  const configContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from Strapi configuration
// Generated at: ${new Date().toISOString()}
// Source: ${source}
// Total locales: ${uniqueLocales.length}

export const locales = ${JSON.stringify(uniqueLocales)} as const;
export const defaultLocale = '${defaultLocale}' as const;
export type Locale = typeof locales[number];

// Strapi语言代码映射
export const strapiLocaleMap: Record<Locale, string> = {
  ${uniqueLocales.map(locale => `'${locale}': '${locale}'`).join(',\n  ')}
} as const;

// 获取语言显示名称（使用 Strapi 返回的名称）
export function getLanguageName(locale: Locale): string {
  const names: Record<Locale, string> = {
    ${localeDetails.map(l => `'${l.code}': '${l.name}'`).join(',\n    ')}
  };
  return names[locale] || locale;
}

// 获取格式化区域设置（无硬编码的通用规则）
export function getLocaleForFormatting(locale: Locale): string {
  // 通用规则：如果已经是语言-地区格式则保留，否则将语言代码转换为语言-地区（如 en → en-US）
  const formatLocale = (l: string): string => {
    if (/^[a-z]{2}-[A-Z]{2}$/.test(l)) return l;
    if (/^[a-z]{2}$/.test(l)) return \`\${l}-\${l.toUpperCase()}\`;
    return l;
  };
  return formatLocale(locale);
}

// 获取HTML lang属性（直接使用语言代码）
export function getHtmlLang(locale: Locale): string {
  return locale;
}

export function getConfig() {
  return {
    locales,
    defaultLocale,
    strapiLocaleMap,
    getLanguageName,
    getLocaleForFormatting,
    getHtmlLang
  };
}

// 构建GraphQL查询别名（用于动态查询构建）
export function buildBlogsQueryAliases(): string {
  return locales.map(locale => \`
    \${locale}Blogs: blogs(
      locale: "\${locale}"
      sort: "publishedAt:desc"
      pagination: { limit: 100 }
    ) {
      documentId
      slug
      title
      author
      content
      locale
      publishedAt
      createdAt
      updatedAt
      cover {
        url
        alternativeText
      }
    }
  \`).join('\\n');
}

// 构建博客字段查询
export const BLOG_FIELDS = \`
  documentId
  slug
  title
  author
  content
  locale
  publishedAt
  createdAt
  updatedAt
  cover {
    url
    alternativeText
  }
\`;
`;

  // 确保目录存在并写入文件
  const outputDir = join(__dirname, '../src/generated');
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = join(outputDir, 'i18n-config.ts');
  writeFileSync(outputPath, configContent, 'utf8');

  console.log(`\n✅ Successfully generated i18n-config.ts`);
  console.log(`📁 Output: ${outputPath}`);

  return { locales: uniqueLocales, defaultLocale };
}

// 后备配置（所有方法失败时使用）
function generateFallbackConfig(): void {
  console.log('\n⚠️ Using fallback configuration');

  const fallbackConfig = `// AUTO-GENERATED FILE - FALLBACK CONFIGURATION
// Generated at: ${new Date().toISOString()}

export const locales = ['en', 'es'] as const;
export const defaultLocale = 'en' as const;
export type Locale = typeof locales[number];

export const strapiLocaleMap: Record<Locale, string> = {
  'en': 'en',
  'es': 'es',
} as const;

export function getLanguageName(locale: Locale): string {
  const names: Record<Locale, string> = {
    'en': 'English',
    'es': 'Español',
  };
  return names[locale] || locale;
}

export function getLocaleForFormatting(locale: Locale): string {
  const formatLocale = (l: string): string => {
    if (/^[a-z]{2}-[A-Z]{2}$/.test(l)) return l;
    if (/^[a-z]{2}$/.test(l)) return \`\${l}-\${l.toUpperCase()}\`;
    return l;
  };
  return formatLocale(locale);
}

export function getHtmlLang(locale: Locale): string {
  return locale === 'es' ? 'es-ES' : 'en-US';
}

export function getConfig() {
  return {
    locales,
    defaultLocale,
    strapiLocaleMap,
    getLanguageName,
    getLocaleForFormatting,
    getHtmlLang
  };
}

export function buildBlogsQueryAliases(): string {
  return locales.map(locale => \`
    \${locale}Blogs: blogs(
      locale: "\${locale}"
      sort: "publishedAt:desc"
      pagination: { limit: 100 }
    ) {
      documentId
      slug
      title
      author
      content
      locale
      publishedAt
      createdAt
      updatedAt
      cover {
        url
        alternativeText
      }
    }
  \`).join('\\n');
}

export const BLOG_FIELDS = \`
  documentId
  slug
  title
  author
  content
  locale
  publishedAt
  createdAt
  updatedAt
  cover {
    url
    alternativeText
  }
\`;
`;

  const outputDir = join(__dirname, '../src/generated');
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = join(outputDir, 'i18n-config.ts');
  writeFileSync(outputPath, fallbackConfig, 'utf8');

  console.log(`✅ Generated fallback i18n-config.ts`);
  console.log(`📁 Output: ${outputPath}`);
}

// 主函数
async function fetchStrapiConfig(): Promise<void> {
  try {
    console.log('🚀 Starting Strapi configuration fetch...');
    console.log(`🔗 URL: ${STRAPI_URL}`);
    console.log(`🔑 Token: ${STRAPI_TOKEN ? 'Provided' : 'Not provided (public access)'}`);

    const localesResult = await fetchLocalesViaRestAPI();

    if (localesResult && localesResult.data) {
      generateConfig(localesResult.data, localesResult.source);
      return;
    }

    throw new Error('Could not retrieve locales using REST API');

  } catch (error: any) {
    console.error('❌ Failed to fetch Strapi configuration:', error instanceof Error ? error.message : String(error));
    generateFallbackConfig();
  }
}

fetchStrapiConfig();
