// scripts/fetch-strapi-config.ts
import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import 'dotenv/config';

const __dirname = dirname(fileURLToPath(import.meta.url));

const STRAPI_URL = process.env.PUBLIC_STRAPI_API_URL;
const STRAPI_TOKEN = process.env.PUBLIC_STRAPI_API_TOKEN;

if (!STRAPI_URL) {
  console.error('PUBLIC_STRAPI_API_URL environment variable is not set');
  process.exit(1);
}

interface StrapiLocale {
  code: string;
  name: string;
  isDefault?: boolean;
}

interface LocalesResult {
  data: StrapiLocale[];
  source: string;
}

// ========== 原有的获取语言列表函数（不变） ==========
async function fetchLocalesViaRestAPI(): Promise<LocalesResult | null> {
  console.log('\n🌐 Fetching locales via REST API...');
  try {
    const response = await fetch(`${STRAPI_URL}/api/i18n/locales`, {
      headers: STRAPI_TOKEN ? { Authorization: `Bearer ${STRAPI_TOKEN}` } : {}
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const data = await response.json();
    if (data && data.length > 0) {
      console.log(`✅ Successfully fetched ${data.length} locales via REST API`);
      const localesData = data.map((locale: any) => ({
        code: locale.code || '',
        name: locale.name || '',
        isDefault: locale.isDefault === true || locale.default === true,
      }));
      return { data: localesData, source: 'REST API' };
    }
    throw new Error('No locales data from REST API');
  } catch (error: any) {
    console.error('❌ REST API failed:', error.message);
    return null;
  }
}

function fallbackLocaleName(code: string): string {
  return code.charAt(0).toUpperCase() + code.slice(1);
}

// 生成 i18n-config.ts（原有逻辑）
function generateConfig(localesData: StrapiLocale[], source: string): { locales: string[]; defaultLocale: string } {
  console.log(`\n📁 Generating configuration from: ${source}`);

  const validLocales = localesData
    .map(item => item.code?.trim())
    .filter((code): code is string => !!code);

  const uniqueLocales = [...new Set(validLocales)];
  if (uniqueLocales.length === 0) {
    throw new Error('No valid locale codes found');
  }

  let defaultLocale = uniqueLocales[0];
  const defaultItem = localesData.find(item => item.isDefault === true);
  if (defaultItem?.code) {
    defaultLocale = defaultItem.code;
  } else {
    console.warn(`⚠️ No default locale marker found, using first locale '${defaultLocale}' as default.`);
  }

  console.log(`📋 Found ${uniqueLocales.length} locales: ${uniqueLocales.join(', ')}`);
  console.log(`   Default locale: ${defaultLocale}`);

  const localeDetails = uniqueLocales.map(code => {
    const item = localesData.find(i => i.code === code);
    return {
      code,
      name: item?.name || fallbackLocaleName(code),
      isDefault: code === defaultLocale
    };
  });

  const configContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from Strapi configuration
// Generated at: ${new Date().toISOString()}
// Source: ${source}
// Total locales: ${uniqueLocales.length}

export const locales = ${JSON.stringify(uniqueLocales)} as const;
export const defaultLocale = '${defaultLocale}' as const;
export type Locale = typeof locales[number];

// Strapi语言代码映射
export const strapiLocaleMap: Record<Locale, string> = {
  ${uniqueLocales.map(locale => `'${locale}': '${locale}'`).join(',\n  ')}
} as const;

// 获取语言显示名称（使用 Strapi 返回的名称）
export function getLanguageName(locale: Locale): string {
  const names: Record<Locale, string> = {
    ${localeDetails.map(l => `'${l.code}': '${l.name}'`).join(',\n    ')}
  };
  return names[locale] || locale;
}

// 获取格式化区域设置（无硬编码的通用规则）
export function getLocaleForFormatting(locale: Locale): string {
  const formatLocale = (l: string): string => {
    if (/^[a-z]{2}-[A-Z]{2}$/.test(l)) return l;
    if (/^[a-z]{2}$/.test(l)) return \`\${l}-\${l.toUpperCase()}\`;
    return l;
  };
  return formatLocale(locale);
}

// 获取HTML lang属性（直接使用语言代码）
export function getHtmlLang(locale: Locale): string {
  return locale;
}

export function getConfig() {
  return {
    locales,
    defaultLocale,
    strapiLocaleMap,
    getLanguageName,
    getLocaleForFormatting,
    getHtmlLang
  };
}

// 构建GraphQL查询别名（用于动态查询构建）
export function buildBlogsQueryAliases(): string {
  return locales.map(locale => \`
    \${locale}Blogs: blogs(
      locale: "\${locale}"
      sort: "publishedAt:desc"
      pagination: { limit: 100 }
    ) {
      documentId
      slug
      title
      author
      content
      locale
      publishedAt
      createdAt
      updatedAt
      cover {
        url
        alternativeText
      }
    }
  \`).join('\\n');
}

// 构建博客字段查询
export const BLOG_FIELDS = \`
  documentId
  slug
  title
  author
  content
  locale
  publishedAt
  createdAt
  updatedAt
  cover {
    url
    alternativeText
  }
\`;
`;

  const outputDir = join(__dirname, '../src/generated');
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = join(outputDir, 'i18n-config.ts');
  writeFileSync(outputPath, configContent, 'utf8');

  console.log(`\n✅ Successfully generated i18n-config.ts`);
  console.log(`📁 Output: ${outputPath}`);

  return { locales: uniqueLocales, defaultLocale };
}

function generateFallbackConfig(): void {
  console.log('\n⚠️ Using fallback configuration');

  const fallbackConfig = `// AUTO-GENERATED FILE - FALLBACK CONFIGURATION
// Generated at: ${new Date().toISOString()}

export const locales = ['en', 'es'] as const;
export const defaultLocale = 'en' as const;
export type Locale = typeof locales[number];

export const strapiLocaleMap: Record<Locale, string> = {
  'en': 'en',
  'es': 'es',
} as const;

export function getLanguageName(locale: Locale): string {
  const names: Record<Locale, string> = {
    'en': 'English',
    'es': 'Español',
  };
  return names[locale] || locale;
}

export function getLocaleForFormatting(locale: Locale): string {
  const formatLocale = (l: string): string => {
    if (/^[a-z]{2}-[A-Z]{2}$/.test(l)) return l;
    if (/^[a-z]{2}$/.test(l)) return \`\${l}-\${l.toUpperCase()}\`;
    return l;
  };
  return formatLocale(locale);
}

export function getHtmlLang(locale: Locale): string {
  return locale === 'es' ? 'es-ES' : 'en-US';
}

export function getConfig() {
  return {
    locales,
    defaultLocale,
    strapiLocaleMap,
    getLanguageName,
    getLocaleForFormatting,
    getHtmlLang
  };
}

export function buildBlogsQueryAliases(): string {
  return locales.map(locale => \`
    \${locale}Blogs: blogs(
      locale: "\${locale}"
      sort: "publishedAt:desc"
      pagination: { limit: 100 }
    ) {
      documentId
      slug
      title
      author
      content
      locale
      publishedAt
      createdAt
      updatedAt
      cover {
        url
        alternativeText
      }
    }
  \`).join('\\n');
}

export const BLOG_FIELDS = \`
  documentId
  slug
  title
  author
  content
  locale
  publishedAt
  createdAt
  updatedAt
  cover {
    url
    alternativeText
  }
\`;
`;

  const outputDir = join(__dirname, '../src/generated');
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = join(outputDir, 'i18n-config.ts');
  writeFileSync(outputPath, fallbackConfig, 'utf8');

  console.log(`✅ Generated fallback i18n-config.ts`);
  console.log(`📁 Output: ${outputPath}`);
}

// ========== 新增：翻译获取与生成 ==========
interface TranslationItem {
  key: string;
  value: string;
}

/**
 * 将点号分隔的 key 转换为嵌套对象
 * 例如 "common.readMore" => { common: { readMore: "value" } }
 */
function setNestedValue(obj: any, path: string, value: string): void {
  const keys = path.split('.');
  let current = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i];
    if (!current[key]) current[key] = {};
    current = current[key];
  }
  current[keys[keys.length - 1]] = value;
}

/**
 * 从 Strapi 获取指定语言的所有翻译条目（自动处理分页）
 */
async function fetchTranslationsForLocale(locale: string): Promise<Record<string, string>> {
  const baseUrl = `${STRAPI_URL}/api/translations`;
  let page = 1;
  const pageSize = 100;
  let hasMore = true;
  const allItems: TranslationItem[] = [];

  while (hasMore) {
    const url = `${baseUrl}?locale=${locale}&pagination[page]=${page}&pagination[pageSize]=${pageSize}`;
    const response = await fetch(url, {
      headers: STRAPI_TOKEN ? { Authorization: `Bearer ${STRAPI_TOKEN}` } : {},
    });
    if (!response.ok) {
      throw new Error(`Failed to fetch translations for ${locale}: ${response.status}`);
    }
    const json = await response.json();
    const items = json.data as Array<{ key: string; value: string }>;
    if (!items.length) break;
    allItems.push(...items.map((item) => ({ key: item.key, value: item.value })));
    const total = json.meta?.pagination?.total || 0;
    if (page * pageSize >= total) hasMore = false;
    else page++;
  }

  const result: Record<string, string> = {};
  for (const item of allItems) {
    result[item.key] = item.value;
  }
  return result;
}

/**
 * 生成 translations.ts 文件
 */
async function generateTranslationsFile(locales: string[]): Promise<void> {
  console.log('\n🌐 Fetching translations from Strapi...');
  const allTranslations: Record<string, any> = {};

  for (const locale of locales) {
    try {
      const flatMap = await fetchTranslationsForLocale(locale);
      const nested: any = {};
      for (const [key, value] of Object.entries(flatMap)) {
        setNestedValue(nested, key, value);
      }
      allTranslations[locale] = nested;
      console.log(`✅ Fetched ${Object.keys(flatMap).length} translations for ${locale}`);
    } catch (err) {
      console.error(`❌ Failed to fetch translations for ${locale}:`, err);
      // 降级：使用空对象，避免构建失败
      allTranslations[locale] = {};
    }
  }

  // 生成 TypeScript 文件
  const outputDir = join(__dirname, '../src/generated');
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }
  const outputPath = join(outputDir, 'translations.ts');
  const fileContent = `// AUTO-GENERATED by fetch-strapi-config.ts
// DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}

import type { I18nDict } from '@/i18n/dict';

export const translations: Record<string, I18nDict> = ${JSON.stringify(allTranslations, null, 2)};
`;
  writeFileSync(outputPath, fileContent);
  console.log(`✅ Translations saved to ${outputPath}`);
}

// 后备翻译生成（当无法获取 locales 时）
async function generateFallbackTranslations(): Promise<void> {
  console.log('\n⚠️ Using fallback translations (empty)');
  const fallbackLocales = ['en', 'es', 'fr'];
  const allTranslations: Record<string, any> = {};
  for (const locale of fallbackLocales) {
    allTranslations[locale] = {};
  }
  const outputDir = join(__dirname, '../src/generated');
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }
  const outputPath = join(outputDir, 'translations.ts');
  const fileContent = `// AUTO-GENERATED (fallback) - DO NOT EDIT
// Generated at: ${new Date().toISOString()}

import type { I18nDict } from '@/i18n/dict';

export const translations: Record<string, I18nDict> = ${JSON.stringify(allTranslations, null, 2)};
`;
  writeFileSync(outputPath, fileContent);
  console.log(`✅ Fallback translations saved to ${outputPath}`);
}

// ========== 主函数（整合原有逻辑和新增翻译生成） ==========
async function fetchStrapiConfig(): Promise<void> {
  try {
    console.log('🚀 Starting Strapi configuration fetch...');
    console.log(`🔗 URL: ${STRAPI_URL}`);
    console.log(`🔑 Token: ${STRAPI_TOKEN ? 'Provided' : 'Not provided (public access)'}`);

    const localesResult = await fetchLocalesViaRestAPI();

    if (localesResult && localesResult.data) {
      const { locales } = generateConfig(localesResult.data, localesResult.source);
      // 生成翻译文件
      await generateTranslationsFile(locales);
      return;
    }

    throw new Error('Could not retrieve locales using REST API');
  } catch (error: any) {
    console.error('❌ Failed to fetch Strapi configuration:', error instanceof Error ? error.message : String(error));
    generateFallbackConfig();
    await generateFallbackTranslations();
  }
}

fetchStrapiConfig();
